add rate api and job runner to ci and reactivate ci endpoint test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,26 +14,33 @@ jobs:
         working-directory: ./dynamic-pricing
     steps:
     - uses: actions/checkout@v4
+    - name: Create Docker network
+      run: docker network create ci-network
     - name: Build Docker image
       run: docker build -t interview-app .
-    - name: Run the container
-      run: docker run -d -p 3000:3000 -v $(pwd):/workspaces/dynamic-pricing --name interview-dev interview-app
+    - name: Run the rate-api container
+      run: docker run -d -p 8080:8080 --network ci-network --name rate-api tripladev/rate-api
+    - name: Run the Rails container
+      run: docker run -d -p 3000:3000 -v $(pwd):/workspaces/dynamic-pricing --network ci-network -e RATE_API_URL=http://rate-api:8080 -e RATE_API_KEY=04aa6f42aa03f220c2ae9a276cd68c62 --name interview-dev interview-app
+    - name: Wait for containers to be ready
+      run: sleep 5
+    - name: Run perform_now job to initialize the hotel room prices
+      run: docker container exec interview-dev ./bin/rails runner "UpdateHotelRoomPricesJob.perform_now"
     - name: Run all tests
       run: docker container exec interview-dev ./bin/rails test
-    # TODO: consider reenabling this after implementing the regular jobs to seed data in the rate-api
-    # - name: Test API endpoint returns 200
-    #   run: |
-    #     echo "Testing API endpoint..."
-    #     for i in {1..10}; do
-    #       echo "Attempt $i/10: Testing pricing endpoint..."
-    #       HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" 'http://localhost:3000/pricing?period=Summer&hotel=FloatingPointResort&room=SingletonRoom' || echo "000")
-    #       if [ "$HTTP_STATUS" -eq 200 ]; then
-    #         echo "✅ API endpoint returned HTTP 200"
-    #         exit 0
-    #       else
-    #         echo "❌ API endpoint returned HTTP $HTTP_STATUS, retrying in 3 seconds..."
-    #         sleep 3
-    #       fi
-    #     done
-    #     echo "❌ API endpoint failed after 10 attempts"
-    #     exit 1
+    - name: Test API endpoint returns 200
+      run: |
+        echo "Testing API endpoint..."
+        for i in {1..10}; do
+          echo "Attempt $i/10: Testing pricing endpoint..."
+          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" 'http://localhost:3000/pricing?period=Summer&hotel=FloatingPointResort&room=SingletonRoom' || echo "000")
+          if [ "$HTTP_STATUS" -eq 200 ]; then
+            echo "✅ API endpoint returned HTTP 200"
+            exit 0
+          else
+            echo "❌ API endpoint returned HTTP $HTTP_STATUS, retrying in 3 seconds..."
+            sleep 3
+          fi
+        done
+        echo "❌ API endpoint failed after 10 attempts"
+        exit 1
